package application;

import java.util.ArrayList;
import java.util.HashMap;

import Card.MilitaryCard;
import Card.PointCard;
import Card.RawMaterialCard;
import Card.TradingCard;
import Card.base.Card;

public class InitialCardDeck {
	public ArrayList<Card> startingCard; 
	public ArrayList<Card> midGameCard ;
	public ArrayList<Card> lateGameCard ;
	
	public InitialCardDeck() {
		//cardAgeOne
		this.startingCard = new ArrayList<Card>();
		this.startingCard.add(new MilitaryCard("Volcano Card",new HashMap<String,Integer>(),1,"")) ;
		this.startingCard.add(new MilitaryCard("Volcano Card",new HashMap<String,Integer>(),1,"")) ;
		HashMap<String,Integer> cost  = new HashMap<String,Integer>() ;
		cost.put("Polymerization Preparation",1) ;
		this.startingCard.add(new MilitaryCard("Ambriel",cost,1,"Laternora")) ;
		cost.clear();
		cost.put("D32Steel", 1) ;
		this.startingCard.add(new MilitaryCard("Ifrit",cost,1,"Rhine Lab")) ;
		cost.clear();
		cost.put("LMD",2) ;
		this.startingCard.add(new MilitaryCard("EarthSpirit",cost,1,"Leithanien")) ;
		cost.clear();
		this.startingCard.add(new PointCard("Lappland",cost,3,"Rhodes Island"));
		this.startingCard.add(new PointCard("Istina",cost,3,"Ursus"));
		cost.put("Bipolar Nanoflake",3) ;
		this.startingCard.add(new PointCard("Meteor",cost,3,"Kazimierz")) ;
		cost.clear();
		HashMap<String,Integer> reward = new HashMap<String,Integer>() ;
		reward.put("Polymerization Preparation",1) ;
		this.startingCard.add(new RawMaterialCard("Cuora",cost,reward)) ;
		cost.clear();
		cost.put("LMD", 1) ;
		this.startingCard.add(new RawMaterialCard("Cuora",cost,reward)) ;
		cost.clear();
		reward.clear();
		reward.put("D32Steel",1);
		this.startingCard.add(new RawMaterialCard("Courior",cost,reward)) ;
		cost.put("LMD", 1) ;
		this.startingCard.add(new RawMaterialCard("Matterhorn",cost,reward)) ;
		cost.clear();
		reward.clear();
		reward.put("Bipolar Nanoflake",1);
		this.startingCard.add(new RawMaterialCard("Shirayuki",cost,reward)) ;
		cost.put("LMD", 1) ;
		this.startingCard.add(new RawMaterialCard("FlameBringer",cost,reward)) ;
		reward.clear();
		reward.put("Manganese Ore",1);
		this.startingCard.add(new RawMaterialCard("Out-country",cost,reward)) ;
		reward.clear();
		reward.put("Sugar Pack",1);
		this.startingCard.add(new RawMaterialCard("Forest",cost,reward)) ;
		cost.put("LMD", 3) ;
		reward.clear();
		this.startingCard.add(new TradingCard("Motoimaru",cost,"",reward,"decreaseBipolarNanoFlakeCost",0)) ;
		this.startingCard.add(new TradingCard("Shaw",cost,"",reward,"decreaseD32SteelCost",0)) ;
		this.startingCard.add(new TradingCard("Dur-Nar",cost,"",reward,"decreasePolymerizationPreparationCost",0)) ;
		cost.clear();
		reward.put("LMD",4);
		this.startingCard.add(new TradingCard("Rope",cost,"Rim Bilition",reward,"",0)) ;
		reward.clear();
		cost.clear();
		//cardAgeTwo
		this.midGameCard = new ArrayList<Card>();
		cost.put("D32Steel",2) ;
		this.midGameCard.add(new MilitaryCard("Reunion's Attack",cost,2,"")) ;
		cost.clear() ;
		cost.put("Polymerization Preparation",2) ;
		this.midGameCard.add(new MilitaryCard("Reunion's Attack",cost,2,"")) ;
		cost.clear() ;
		cost.put("LMD",3) ;
		this.midGameCard.add(new MilitaryCard("Saria",cost,1,"Rhine Lab")) ;
		cost.clear() ;
		cost.put("Bipolar Nanoflake",1) ;
		cost.put("Polymerization Preparation",1) ;
		cost.put("Sugar Pack",1) ;
		this.midGameCard.add(new MilitaryCard("Swire",cost,2,"Lungman")) ;
		cost.clear() ;
		cost.put("Bipolar Nanoflake",1) ;
		cost.put("D32Steel",1) ;
		this.midGameCard.add(new MilitaryCard("Mostima",cost,1,"Laternora")) ;
		cost.clear() ;
		cost.put("D32Steel",2) ;
		cost.put("Manganese Ore",1) ;
		this.midGameCard.add(new MilitaryCard("W",cost,2,"Reunion")) ;
		cost.clear();
		cost.put("Polymerization Preparation", 2) ;
		cost.put("Manganese Ore",1) ;
		this.midGameCard.add(new PointCard("Hellagur",cost,5,""));
		cost.clear();
		cost.put("D32Steel",2) ;
		this.midGameCard.add(new PointCard("Texas",cost,4,"Rhodes Island,Penguin Logistic"));
		cost.clear();
		cost.put("Polymerization Preparation", 1) ;
		cost.put("Sugar Pack",1) ;
		this.midGameCard.add(new PointCard("Zima",cost,4,"Ursus,Victoria"));
		cost.clear();
		cost.put("Bipolar Nanoflake",3) ;
		this.midGameCard.add(new PointCard("Platinum",cost,5,"Kazimierz"));
		cost.clear();
		cost.put("Bipolar Nanoflake",1) ;
		cost.put("Polymerization Preparation", 1) ;
		this.midGameCard.add(new PointCard("Jessica",cost,4,"Black Steel"));
		cost.clear();
		reward.clear();
		cost.put("LMD", 2) ;
		reward.put("Polymerization Preparation",2) ;
		this.midGameCard.add(new RawMaterialCard("Bison",cost,reward)) ;
		reward.clear();
		reward.put("D32Steel",2) ;
		this.midGameCard.add(new RawMaterialCard("Vigna",cost,reward)) ;
		reward.clear();
		reward.put("Bipolar Nanoflake",2) ;
		this.midGameCard.add(new RawMaterialCard("Grani",cost,reward)) ;
		cost.clear();
		reward.clear();
		reward.put("Manganese Ore",1);
		this.midGameCard.add(new RawMaterialCard("Cave",cost,reward)) ;
		reward.clear();
		reward.put("Sugar Packe",1);
		this.midGameCard.add(new RawMaterialCard("Village",cost,reward)) ;
		cost.clear();
		reward.clear();
		cost.put("LMD",3) ;
		cost.put("D32Steel",1) ;
		reward.put("Manganese Ore",1);
		reward.put("Sugar Packe",1);
		this.midGameCard.add(new TradingCard("Manticore",cost,"",reward,"",0)) ;
		cost.clear();
		reward.clear();
		cost.put("LMD",2) ;
		cost.put("Manganese Ore",1);
		cost.put("Sugar Packe",1) ;
		reward.put("D32Steel",1) ;
		reward.put("Bipolar Nanoflake",1) ;
		reward.put("Polymerization Preparation",1) ;
		this.midGameCard.add(new TradingCard("Executor",cost,"",reward,"",0)) ;
		cost.clear();
		reward.clear();
		cost.put("LMD",4) ;
		this.midGameCard.add(new TradingCard("Cliffheart",cost,"",reward,"decreaseManganeseAndSugerCost",0)) ;
		cost.clear();
		reward.clear();
		reward.put("LMD",6) ;
		this.midGameCard.add(new TradingCard("Pramanix",cost,"Kjerag",reward,"",0)) ;
		reward.clear();
		cost.clear();
		//cardAgeThree
		this.lateGameCard = new ArrayList<Card>();
		cost.put("D32Steel",3) ;
		cost.put("Polymerization Preparation",2) ;
		this.lateGameCard.add(new MilitaryCard("Reunion's Squad",cost,3,"")) ;
		cost.clear();
		cost.put("LMD",8) ;
		this.lateGameCard.add(new MilitaryCard("Skullshatterer",cost,3,"")) ;
		cost.clear();
		cost.put("Bipolar Nanoflake",2);
		cost.put("D32Steel",1);
		cost.put("Sugar Packe",1) ;
		this.lateGameCard.add(new MilitaryCard("Eyjafjalla",cost,2,"Leithanien")) ;
		cost.clear();
		cost.put("Polymerization Preparation",3) ;
		cost.put("Manganese Ore",1);
		this.lateGameCard.add(new MilitaryCard("Ch'en",cost,2,"Lungman")) ;
		cost.clear();
		cost.put("D32Steel",2) ;
		cost.put("Bipolar Nanoflake",2);
		this.lateGameCard.add(new MilitaryCard("Tulula",cost,2,"Reunion")) ;
		cost.clear();
		reward.clear();
		cost.put("D32Steel",1) ;
		cost.put("Bipolar Nanoflake",1);
		cost.put("Polymerization Preparation",1) ;
		cost.put("Manganese Ore",2);
		this.lateGameCard.add(new PointCard("Mayer",cost,7,""));
		cost.clear();
		cost.put("Bipolar Nanoflake",3);
		cost.put("Polymerization Preparation",2) ;
		this.lateGameCard.add(new PointCard("Aak",cost,7,""));
		cost.clear();
		cost.put("Bipolar Nanoflake",2);
		cost.put("Manganese Ore",1);
		this.lateGameCard.add(new PointCard("Hoshiguma",cost,5,""));
		cost.clear();
		cost.put("D32Steel",2) ;
		cost.put("Polymerization Preparation",2) ;
		this.lateGameCard.add(new PointCard("Exusial",cost,6,"Penguin Logistic"));
		cost.clear();
		cost.put("D32Steel",1) ;
		cost.put("Polymerization Preparation",1) ;
		cost.put("Sugar Packe",2) ;
		this.lateGameCard.add(new PointCard("Siege",cost,6,"Victoria"));
		cost.clear();
		cost.put("D32Steel",2) ;
		cost.put("Bipolar Nanoflake",1);
		cost.put("Sugar Packe",1) ;
		this.lateGameCard.add(new PointCard("Liskarm",cost,5,"Black Steel"));
		cost.clear();
		cost.put("Sugar Packe",2) ;
		this.lateGameCard.add(new TradingCard("Hung",cost,"",reward,"",3)) ;
		cost.clear();
		cost.put("Polymerization Preparation",1) ;
		cost.put("Sugar Packe",1) ;
		cost.put("Manganese Ore",1);
		this.lateGameCard.add(new TradingCard("Nightingale",cost,"",reward,"",3)) ;
		cost.clear();
		cost.put("Bipolar Nanoflake",2);
		cost.put("Manganese Ore",1);
		this.lateGameCard.add(new TradingCard("Magallan",cost,"",reward,"",3)) ;
		cost.clear();
		cost.put("D32Steel",2) ;
		cost.put("Manganese Ore",1);
		this.lateGameCard.add(new TradingCard("Savage",cost,"Rim Bilition",reward,"",3)) ;
		cost.clear();
		cost.put("D32Steel",1) ;
		cost.put("Bipolar Nanoflake",1);
		cost.put("Polymerization Preparation",1) ;
		this.lateGameCard.add(new TradingCard("Silverash",cost,"Kazimierz",reward,"",3)) ;
	}
}
